### ISSUE TITLE
Graph GAN initial experiments

### ISSUE THREAD

**Issue by bigaidream** [rahul99/msc_plan#1]
We need to decide:
1. Which dataset to use?
2. Which graph neural network to use to encode the graph input (let's try Graph Convolutional Network first?)
3. Which conditional GAN to use?

**Comment by rahul99** [comment]
Hi Jie,

1. For datasets, authors of Pose estimation used standard "DeepFasion" and "Market-1501" dataset. However, I am not sure, how relevant these datasets would be, because looking at the sample images, there is just one object (a human figure) and the graph will have limited info to fetch relationship between objects.

There is another paper by Ruslan and team - "Show, Attend and Tell: Neural Image Caption
Generation with Visual Attention". They have used benchmark datasets: "Flickr8k", "Flickr30k", "MS COCO". I checked that these datasets are accessible. Shall we go ahead with this?

2. Yes, to start with, we can use CNN to encode graph information. 

3. For this, could explain in a little bit more detail. 

PS. Please also share with me the details on how to extract graph information. What are the available tools in-house.

**Comment by rahul99** [comment]
1. COCO Dataset
http://mscoco.org/dataset/#download

2. Flickr8k
https://illinois.edu/fb/sec/1713398

3. Flickr30k
http://shannon.cs.illinois.edu/DenotationGraph/

I have filled up the form to request these datasets.

**Comment by bigaidream** [comment]
2. For Graph Convolutional Neural Networks, please refer to this blog post and the associated code: https://tkipf.github.io/graph-convolutional-networks/

3. Can we use this as our code base? https://github.com/kaonashi-tyc/zi2zi

P.S: no need to say `Jie` anymore :smirk:

**Comment by bigaidream** [comment]
https://github.com/woozzu/dong_iccv_2017

**Comment by rahul99** [comment]
1. Looking into it in detail. Seems useful. 

2. Also, help with connecting to the GPU. Yesterday, I have setup Tensorflow in my Machine until we have access to the GPU. I have never used GPU before. Will it have all the dependencies already installed?

3. Can we talk on Skype today evening perhaps? Need to understand a few things. We can keep a Skype call once or twice per week.

**Comment by bigaidream** [comment]
GPU server: `jie@172.29.31.109`, password: `youguess?`. This server has all the GPU stuff and TensorFlow. 

---

My skype is `fujie5098`. OK, tonight 10pm?

**Comment by rahul99** [comment]
10 PM it is :)
